folder_in: /home/user/folder_in
folder_out: /home/user/folder_out
folder_ext: /home/user/folder_ex
folder_badarx: /home/user/tst/badarx
#folder_home: /home/user/tst/home
count: 10
bs: 5M
format_arch: '*.7z'
